variable "vpc_state_key" {}
variable "security_groups_state_key" {}
variable "ui_state_key" {}
variable "server_state_key" {}
variable "aws_region" {}
variable "availability_zone_1" {}
variable "availability_zone_2" {}
variable "availability_zone_3" {}
variable "tfstate_bucket_name" {}
variable "prefix" {}
variable "dns_zone_id" {}
variable "root_domain" {}
variable "sub_domain" {}